language: php
php: 7.2

env:
  global:

    - TM_WP_URL=https://aws.tm.id.au

    # TM_WP_REST_API_TOKEN
    - secure: NJR/HHrsibGFrAOhEG+muooXxsGOepCa8n3VlItbHR/q3ETRXLqqZLjXVu+YwrCQoFqVRSuD23ET1/rx7U+aY4paEUL5bEsqSRfwpz39JZ392+qxyreFlXbyIKd2zIyu57GIJqCb4GAeKSeiOjpeeZIQuJkzOHka4NSB3Yy2o/BR8r9KuZzt6UNFIwovgGc3VfbfeHQd2I4CB+p+JotWEFIrfCNM9JqqP/u8xMfChruN7zImiwb2T2juVcnTfRoAZE6FshY0maOdrVbFcpBYjRkdtFDnlLnIV/Le+7+pf0tlqgavueapIlbDir+QjNaqBR1k67zieQyoFVXCsb93V9wvqJjkhadSAehBeQWvkuxJuQJu+uaVe+1TidTdOuCQWV3VSp3AQfjlqcCKxb8ZX2WWPLEKQRpi4ERMuePT2BrZpU7xb0H+V8EVh6s/81J/rmWhzoSjWHvQ436vv7h72+bN1U79plpNg8voT/qoCzIMrypl53ulaP+3CpnDoEy8eYvL6msIGLDVRKpNfg75eZx1ZQJIyxJzp1FDXSOG6jFmVj3bIB8xd4igMsb16VC8yW+y4O54fTvz+IBiSyxIL7/+NlDN3LDJKi2tzh/gq4OSlJ8CgGwj3UIxy+4QYtiJNFHyDSQ+0dX0a/yoSj4Xy3OpR4ksL8e06MJ5rVxpNp0=

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - composer install

script:
  - yarn lint
  - yarn test
  - composer lint
  - composer test
  - yarn webpack

deploy:
  - on:
      branch: dev
    provider: script
    script: ./.deploy.sh


notifications:
  email: false
  webhooks:
    urls: https://api.tm.id.au/dev/travis/jobStatus
  slack:
    on_start: always
    rooms:
      - secure: mQ+a+U74D7h5BW/+YgH0aidWbz9vWAZ+AGS5FBn366H3chCX0Px/97ao8xqcCn3uz0Eqt1wd8+Uu9hFO2hPZzVixKzFQoQe7ggsKRHWzfgwQQV7ln94fhICFUkHSSw9Payq/a+g17GKSSutlfAS7nbmwUeYPbsE96mZjD+3sD272xQr4w9Y0+nQIKUNao+PQHPW0A8jOpgKodwXGo0q1FO2y5ckOU+r1AsP087hEbrFVpFjwdKdKCWQhTsZY2HkN9feHZedSLDtbYDet28aCIHQoGrS2tPYHv/ArkGGP8oXXNXOVbMBGtsbwO7xMT3vD2tqpY9/vJYE2SsAtxQpvpFsrG5U4Q3Hn57Bfjse81qV+YbYGkmlOP8Un5ecNApY5TppYkB6Q/DeBAryoOHUta0+jT5e79PFKi789beYi2brd8UpNZUyusspwch4d39qtJ4DIq+pbXSjWUaP4uYtHqs9oWDMguHmrwUtZSbVWYo+tmvdT3s0GUJOR5KQtXLGDQtmfnOnOe4j8g7KPBRG96LignGYPDyw7zSpmoUjH8/o7XRcms1RfkXAAPa5sGnRX4gRn6j+k84pLyranYiMwOlqP6G1tq8t8QeiMDB3vIOwDS4lNnD+8m8d9vRCXDqtqX7NQg3sf/85zDixF+XtV2yuXiig6g4/AnM3oayNgFAk=
